### ISSUE TITLE
More information about the training data

### ISSUE THREAD

**Issue by CNDOTA** [CMACH508/AlphaDrug#2]
Dear authors, I found that in the data 'train-val-data.tsv', the column 'pdbids' is empty.  As mentioned in your paper, "After filtering, we built a dataset with 239,455 protein–ligand pairs among which there are 981 unique protein sequences." I want to analyze the data and models, could you please provide the data 'train-val-data.tsv' including the 'pdbids' attribution and the corresponding training protein data such as in your "test_pdbs" folder? Thank you very much and really nice work!

**Comment by BL-Lac149597870** [comment]
Hi @CNDOTA , our training set only contains **1D** protein-ligand sequence records downloaded from [bindingdb](https://www.bindingdb.org/rwd/bind/chemsearch/marvin/Download.jsp) while pdbids are used for recording **3D** proteins and complex structures. As far as I know, there seems existing no close connections between two kinds of the records(In fact most of the records in bindingdb do not contain any pdbid attributions). So we are sorry that it is impossible to provide the pdbids of each sequence. By the way, 3D information of proteins in the test sets are provided for the Smina program and our Lmser Transformer are actually trained without the 3D information.

**Comment by CNDOTA** [comment]
Thanks very much for your reply!

> Hi @CNDOTA , our training set only contains **1D** protein-ligand sequence records downloaded from [bindingdb](https://www.bindingdb.org/rwd/bind/chemsearch/marvin/Download.jsp) while pdbids are used for recording **3D** proteins and complex structures. As far as I know, there seems existing no close connections between two kinds of the records(In fact most of the records in bindingdb do not contain any pdbid attributions). So we are sorry that it is impossible to provide the pdbids of each sequence. By the way, 3D information of proteins in the test sets are provided for the Smina program and our Lmser Transformer are actually trained without the 3D information.
