### ISSUE TITLE
hierarchy of skip connections

### ISSUE THREAD

**Issue by LULULUDUDU** [CMACH508/AlphaDrug#3]
According to what you said in your paper, you use adding a hierarchy of skip connections from encoder to decoder in the cross attention layer. Recently, we have been trying to recurrent and learn from your code, but we have encountered a problem as follows: We have not found a specific implementation of jumping over the connection layer in your code,.Could you please tell us where this innovation lies in the code？

**Comment by BL-Lac149597870** [comment]
Thank you for showing interest in our work! The implementation of LT can be found in LmserTransformer.py, specifically on Lines 86-87. For a more detailed overview, please refer to Figure 1B in our manuscript.

**Comment by LULULUDUDU** [comment]
Thanks for your reply!&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 中午12:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CMACH508/AlphaDrug] hierarchy of skip connections (Issue #3)





 
Thank you for showing interest in our work! The implementation of LT can be found in LmserTransformer.py, specifically on Lines 86-87. For a more detailed overview, please refer to Figure 1B in our manuscript.
